package com.forca.bruta;

import java.util.ArrayList;
import java.util.List;

public class Programa {

	public static void main(String[] args) {
		long inicio = 0, duracao = 0;

		List<String> padroes = new ArrayList<String>() {{
			add("blandit");
			add("pellentesque");
			add("malesuada");
			add("Phasellus");
			add("Integer");
			add("Suspendisse");
			add("Vestibulum");
			add("cursus");
			add("eleifend");
			add("mauris");
		}};

		String texto500Palavras = 
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam est velit, varius sit amet ligula at, varius commodo risus. Donec hendrerit tellus velit, eu cursus nisi ultricies quis. Nullam posuere faucibus nisi sed posuere. Sed eleifend mauris quis pulvinar dapibus. Donec finibus massa sed leo facilisis, quis hendrerit justo pharetra. Mauris risus ex, rhoncus in augue sed, ullamcorper pretium lectus. Aliquam erat volutpat. Mauris non molestie magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam quis nibh neque. Vivamus dictum lectus vitae dapibus vulputate. Morbi vestibulum quis sem id consequat. Suspendisse viverra volutpat pretium. Duis erat erat, tempus nec commodo in, venenatis et erat."
				+ "Cras blandit ex et malesuada suscipit. Donec aliquet nibh ut metus cursus, et lobortis nulla fringilla. Proin quis pellentesque odio. Vestibulum fermentum neque eget tincidunt mollis. Nullam auctor sapien ut leo vehicula iaculis. Etiam tincidunt euismod efficitur. Phasellus fermentum imperdiet scelerisque. Integer ante tortor, tincidunt nec sagittis non, ultricies non erat. Suspendisse non lacinia libero. Etiam et mi a enim euismod ultrices pulvinar congue massa. Nulla tempus eleifend justo pulvinar finibus. Aliquam dapibus euismod venenatis."
				+ "Donec eu metus enim. Nam pulvinar dolor a placerat venenatis. Suspendisse molestie tellus neque. In hac habitasse platea dictumst. Etiam commodo dui at urna scelerisque pretium. Vivamus efficitur mi diam, vel consectetur magna iaculis aliquam. Curabitur sed venenatis tellus, in hendrerit neque. Curabitur nec semper est. Sed at odio viverra, ullamcorper tortor vel, consectetur libero. Aenean non eleifend mauris. Quisque interdum tortor a lectus accumsan, nec sodales justo pulvinar. Fusce pellentesque quam massa, pretium hendrerit diam hendrerit vel."
				+ "Nullam vestibulum convallis ante at viverra. Cras in interdum dolor. Aenean eu vestibulum orci, id pellentesque justo. Praesent nec justo aliquam, elementum justo placerat, congue est. Mauris condimentum velit tellus, et venenatis urna fringilla at. Duis a egestas urna. Curabitur ex tortor, convallis quis enim nec, sollicitudin porttitor nisi. Nulla elementum, massa nec cursus pulvinar, turpis dolor pharetra est, eget placerat metus diam sit amet ipsum. Sed scelerisque nibh vel lacus auctor rhoncus. Nullam at lobortis ex. Quisque et mi sagittis, viverra orci vitae, consequat sapien. Fusce sed gravida leo. Nulla facilisi. Proin at arcu at dolor vulputate ullamcorper."
				+ "Aliquam ultricies sodales dolor, malesuada facilisis erat varius sed. Integer vel ipsum augue. Duis sollicitudin elit augue, at congue orci efficitur venenatis. Integer et nisi accumsan, suscipit risus nec, dictum massa. Nullam eu dolor egestas, volutpat ex condimentum, mollis risus. Nam laoreet consectetur metus eu consequat. Curabitur non ante et nisi tempus pharetra."
				+ "Suspendisse pretium dui eget lobortis ultrices. Phasellus a nisi porta, convallis orci ut, tincidunt augue. Pellentesque vitae libero vel massa interdum imperdiet ut non justo. Integer auctor, ipsum viverra dictum tempor, libero lorem hendrerit ex, eget sodales sem lectus at est. Vestibulum pellentesque ut mi eu tempor. Mauris id condimentum libero, eu varius tellus. Suspendisse et aliquet risus, sit amet sagittis odio. Integer at maximus turpis. Cras sodales libero non lectus porta elementum. Quisque in fringilla tortor, quis lacinia tellus. Donec placerat rhoncus enim sed auctor.";
				
		String texto1000Palavras = 
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc magna quam, cursus et mauris id, ornare semper orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum efficitur tellus orci, eget rutrum lectus lacinia consectetur. Morbi dapibus nec nisl sit amet eleifend. Integer dolor turpis, venenatis et elit vitae, dignissim faucibus enim. Ut eu libero sed orci congue commodo vel non mi. Nulla facilisi. Sed ultrices lorem tincidunt, malesuada ipsum consectetur, mollis nisi. Mauris dapibus diam sed tempor aliquet. Mauris congue varius ante, sed finibus sem placerat nec. In dolor nulla, ullamcorper a pulvinar quis, sodales a dolor. Ut tristique at quam tincidunt porta. Morbi sed porttitor lectus."
				+ "Mauris hendrerit neque nec efficitur molestie. Quisque nec pretium lacus. Duis ante purus, porttitor tincidunt convallis nec, blandit et dolor. In pellentesque dui sed enim interdum dapibus at ac lectus. Fusce eget porta erat, ut semper mi. Vivamus pulvinar mauris dolor, non vulputate orci fringilla ac. Mauris semper justo eu efficitur varius. Aliquam quis ultricies sapien, sed tincidunt sapien. Sed id diam sem. Pellentesque posuere, leo sit amet fringilla vestibulum, enim ligula eleifend risus, eget accumsan nunc odio quis massa. Maecenas a pulvinar libero. Vestibulum ut lectus condimentum, scelerisque erat et, consequat velit. Aenean eu lobortis enim, vitae finibus ex. Pellentesque ut efficitur nisl."
				+ "Pellentesque blandit mi nec blandit vestibulum. Duis in enim id purus commodo semper. Sed tristique blandit odio eget posuere. Etiam quis sapien in nisl varius euismod vestibulum non nibh. Maecenas mattis nibh id convallis aliquet. Duis suscipit tincidunt ex. Vestibulum in felis viverra nisl feugiat ornare dapibus sit amet diam."
				+ "Aliquam erat nulla, tristique a elit at, suscipit varius ipsum. Fusce porttitor sagittis tortor, quis semper mauris dignissim eu. Praesent a interdum nibh. Phasellus elit sem, tempus vel mattis vitae, tincidunt vitae eros. Praesent at suscipit ipsum. Nunc tincidunt eleifend leo, eget tristique nibh egestas vel. Maecenas lobortis egestas orci sed dignissim. Proin a lobortis libero, sed faucibus nibh. Nullam lectus urna, fermentum suscipit efficitur ut, vestibulum vel augue. Donec viverra justo sed eros scelerisque dictum. Nulla sagittis sapien velit, et vulputate ipsum maximus sed. Aliquam id lobortis nibh, ut congue elit. Morbi eu augue id libero convallis maximus. Integer tempor ullamcorper ex in facilisis. Sed lorem sapien, ornare hendrerit sodales eu, venenatis nec nibh."
				+ "Proin blandit erat vel elit dapibus, aliquet condimentum dolor malesuada. Morbi turpis tellus, placerat vitae posuere dictum, porttitor in dui. Aenean rhoncus nunc ipsum, in faucibus risus lacinia sit amet. Suspendisse sit amet euismod lorem, sit amet egestas purus. Vivamus at sem tincidunt, aliquet orci nec, tempus lectus. Nullam non mauris tempor, lacinia ex ut, luctus sapien. Morbi a consectetur diam, et consequat felis. Donec bibendum turpis tempus ex aliquet tempor. Etiam fringilla vulputate ante maximus sodales."
				+ "Aenean tempor sodales tristique. Curabitur eget nisl eget sem aliquam luctus. Aliquam eu eros nec risus semper dignissim a sit amet erat. Integer suscipit nunc vel efficitur vestibulum. Cras mattis commodo justo vitae maximus. Curabitur malesuada sit amet ante vitae pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut nec magna mattis, sollicitudin lacus eget, facilisis ex. Curabitur tincidunt, massa a consequat malesuada, magna est interdum orci, et vulputate diam ligula non nisi. Maecenas venenatis posuere elit ac euismod. Nunc aliquet mollis sapien, ut iaculis risus iaculis quis. Aenean quis sapien condimentum, aliquet velit sit amet, molestie dui. Nulla a ex ultrices mauris finibus eleifend eget quis purus. Donec diam est, suscipit nec quam sit amet, fringilla laoreet turpis. Donec fringilla justo vitae diam dictum bibendum. Etiam rutrum sollicitudin nisi, quis consequat neque hendrerit porttitor."
				+ "Mauris ultricies a eros eget aliquet. Maecenas hendrerit ornare felis sit amet dapibus. Morbi aliquet orci eros, sit amet mollis magna commodo et. Sed est nulla, placerat at elit ut, dictum ornare risus. Cras quis varius nisi, sit amet consectetur velit. Sed dignissim odio dolor, et mollis lorem lacinia sed. Curabitur in mauris orci. Fusce eros tortor, tincidunt non sollicitudin et, interdum ut felis. Phasellus ac risus arcu. Cras nunc ex, iaculis vitae ipsum nec, convallis fermentum quam. Mauris non ligula vehicula, molestie urna vehicula, cursus lorem. Sed dictum vulputate ultrices. Pellentesque quis lectus quis enim tempor ultricies et eu diam."
				+ "Nullam lacinia ex ac sem elementum sodales. Nulla vitae ante et enim facilisis auctor quis non purus. Sed et quam varius, ullamcorper turpis faucibus, volutpat quam. Quisque vel eleifend nibh. Integer a turpis mattis, interdum velit faucibus, vehicula turpis. Duis ac hendrerit mauris. Sed ullamcorper nisi id gravida aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed nec massa turpis. Phasellus erat ex, lobortis vitae tincidunt eget, tincidunt tempus risus."
				+ "Nam quis dapibus libero. Etiam at fermentum felis, sit amet facilisis turpis. Ut varius urna in tempus commodo. Morbi quis sem nec nunc egestas pretium. Mauris elementum purus magna, non iaculis leo ultrices in. Suspendisse nisl turpis, vehicula non enim vel, vestibulum porttitor orci. Phasellus vel tortor vestibulum felis consequat porttitor vitae quis metus. Duis egestas lacus sed sapien fermentum condimentum. Vivamus placerat sagittis sem nec lobortis. In rutrum in magna a pellentesque. Nunc sit amet aliquet nisi, non iaculis nisl. Morbi ultrices elit id elementum tincidunt. Vivamus neque metus, consequat a dignissim at, pharetra ut sem. Aenean porta metus a mollis condimentum."
				+ "Fusce molestie enim fermentum sem tristique, vel tristique leo ullamcorper. Sed quis lectus et leo maximus hendrerit. Duis lobortis congue est vel eleifend. Nullam aliquet neque sit amet tellus tristique, ac sodales libero porta. Duis enim lorem, facilisis id hendrerit ut, mollis ultrices urna. Sed tristique mattis tellus, vel viverra lacus accumsan quis. Cras commodo est eget ultricies cursus. Nam tempor porta augue in ultrices. Vivamus dapibus, quam sit amet posuere volutpat, lacus purus tempor lorem, ac suscipit nulla ante non mi."
				+ "Morbi vestibulum eros velit. Donec vestibulum suscipit turpis, luctus tincidunt lacus congue lacinia. Pellentesque ultricies diam in enim porttitor maximus nec vitae ante. Duis volutpat pellentesque commodo. Sed pulvinar quis sapien in dictum. In hac habitasse platea dictumst.";
		
		String texto1500Palavras =
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor nibh sit amet mauris blandit, ac tincidunt sem dignissim. Pellentesque lobortis tortor a lectus gravida accumsan. Donec vel metus id neque suscipit bibendum sit amet at ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus arcu erat, tincidunt sit amet bibendum ut, euismod vel augue. Nullam tempor ante ac metus hendrerit tincidunt. Ut ullamcorper dictum justo, malesuada tristique ligula. Vestibulum eu purus non sem commodo euismod ac eu mi. Nulla congue mi sit amet augue eleifend, vitae suscipit nisl ultrices. Cras et molestie sapien. Vestibulum accumsan aliquet dignissim."
				+ "Suspendisse dignissim euismod elit nec dapibus. Vivamus porttitor est pellentesque pulvinar laoreet. Aliquam efficitur ligula luctus nunc venenatis sagittis. Donec elementum leo non ipsum ullamcorper convallis. Nulla a tellus sed purus laoreet congue. Maecenas eget mauris tempor mauris tristique interdum. Aliquam malesuada ligula dolor, a convallis risus finibus finibus. Praesent gravida dui eget pellentesque auctor."
				+ "Phasellus condimentum nec ante at laoreet. Integer in erat rutrum nulla imperdiet volutpat id sit amet purus. Donec efficitur bibendum lorem, in sodales nisi elementum et. Maecenas in nisl dapibus, euismod mi consequat, pellentesque est. Nam feugiat massa in dui rhoncus, et aliquam libero suscipit. Fusce eget lacinia libero. Phasellus sit amet lorem at elit fermentum elementum non in velit. Nunc eu nisi tortor. Donec bibendum mi vitae arcu posuere imperdiet. Vestibulum sagittis aliquam ex, ac consectetur lorem ornare placerat. Cras dapibus eleifend ante eget tincidunt. Suspendisse lectus massa, mattis in tristique sit amet, vulputate sit amet orci. Proin fermentum magna ut ultrices maximus. Donec faucibus dui nibh, vitae sagittis augue cursus vel."
				+ "Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut tristique arcu sed tincidunt dignissim. Praesent pulvinar facilisis justo at ullamcorper. Phasellus sit amet tincidunt nisi. Nunc lobortis sagittis posuere. Nullam a convallis ligula, id gravida lectus. Donec congue sodales ipsum, at cursus nulla eleifend a. Fusce sagittis, libero nec hendrerit varius, nulla velit ornare leo, eget tincidunt diam erat et augue. Ut lacinia porta sapien non aliquet. Integer porttitor sodales justo sit amet eleifend. Nunc dictum turpis lacus, vitae malesuada orci pretium pellentesque. Nullam ut est gravida ante rutrum ullamcorper. Phasellus eu luctus nibh. Duis rhoncus felis eget risus auctor eleifend. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus rutrum ex at elit porta ultrices."
				+ "Praesent neque purus, vestibulum ac mi quis, dictum vehicula metus. Sed ultricies ornare sem, faucibus dignissim lacus luctus non. Etiam accumsan est nibh, nec cursus dui ultrices ac. Praesent mi ante, rutrum vitae pharetra feugiat, fringilla at ex. Nulla non varius ligula. Aenean sed tristique erat, a suscipit libero. Nunc at dapibus lectus, a dapibus lorem. Vestibulum nec fermentum purus."
				+ "Praesent quis placerat lorem. Curabitur aliquet dolor ac posuere condimentum. Aliquam tristique et nunc nec tristique. Proin tristique ipsum leo, in cursus quam blandit vitae. Integer rhoncus varius neque, eu consectetur lectus efficitur et. Proin mi mauris, molestie at pretium sit amet, fermentum vitae metus. Nullam vulputate tristique auctor. Nullam at sodales turpis, vel mattis metus. Quisque porttitor lacus et elit venenatis ultricies. Duis quam nulla, viverra quis ornare sit amet, tempor nec ante. In vitae massa eget leo ultricies consequat vel ut odio. Ut feugiat blandit diam, pharetra tempus mauris vehicula sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla pulvinar ornare dui, ac congue nibh suscipit porta. Nulla non convallis lectus. Vivamus interdum sem a metus efficitur pretium."
				+ "Nullam tempus arcu dolor, non varius velit bibendum vitae. Nulla facilisi. Nulla ex neque, feugiat vitae egestas vitae, ornare ac nisi. Duis dolor augue, congue ac lacus in, dictum auctor leo. In volutpat sollicitudin nibh aliquam consectetur. Integer porta eros ut ante ullamcorper gravida. Curabitur vel metus lacinia, mattis nunc non, mattis arcu. Donec in vehicula tellus. Sed pharetra volutpat efficitur. Mauris gravida, tortor quis finibus interdum, sem magna tristique elit, in tincidunt justo tellus id ex. Pellentesque venenatis ultricies condimentum. Donec sodales libero lectus, sed tincidunt sapien ornare id. Maecenas porttitor vestibulum quam id interdum. Curabitur congue quis ipsum sed porttitor. Nulla placerat, lorem id consequat venenatis, felis lorem ultrices nisl, sed sodales ante ipsum interdum velit. Sed nec ante et est eleifend sollicitudin."
				+ "Vestibulum euismod felis est, id pretium diam rutrum eget. Vestibulum sit amet porttitor quam, sit amet egestas massa. Sed sapien tortor, dignissim a ultricies volutpat, tincidunt sit amet nunc. Maecenas maximus neque a odio aliquet, quis ultricies arcu posuere. Fusce molestie massa nec nisl pharetra varius. Aliquam erat volutpat. Aliquam vel lorem ac magna bibendum aliquam ut ut magna. Fusce feugiat arcu at metus sagittis pulvinar."
				+ "Pellentesque molestie at ipsum hendrerit lacinia. Aliquam mollis risus ac molestie rhoncus. Nunc ut fringilla augue. Pellentesque mollis dui eget sapien pulvinar porttitor. Aliquam placerat imperdiet augue et molestie. Maecenas scelerisque aliquet mollis. Ut ut lorem magna."
				+ "Vestibulum semper eu dolor quis faucibus. Nam eu mi quis lorem facilisis congue. Fusce congue dui sed iaculis elementum. Duis ligula ante, pharetra sed posuere quis, interdum sit amet sem. Nullam ut fermentum felis. Curabitur quis orci non augue semper consectetur. Fusce ac dictum risus, ut tempor lacus."
				+ "Vestibulum luctus elit in venenatis posuere. Nulla tempor purus tellus, quis aliquet nisi gravida in. Pellentesque vel bibendum metus. Ut eget aliquet justo, in euismod velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam mollis dapibus dolor ac laoreet. Proin gravida augue ut pulvinar condimentum. Nunc orci orci, feugiat ut lacus vehicula, vulputate dignissim dolor."
				+ "Curabitur laoreet porttitor posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse at odio quis lectus semper porttitor eu sed purus. In pretium neque mi, quis accumsan tellus tempor eget. Nam vel suscipit velit, id aliquam sem. Nulla metus orci, euismod eu finibus eget, varius sed libero. Proin congue ligula orci. Duis ex est, suscipit sed metus eget, iaculis dignissim massa. Donec leo odio, sollicitudin fermentum mollis eu, rutrum congue lorem. Aliquam erat volutpat. Donec fermentum diam leo, id aliquet libero eleifend in. Pellentesque viverra orci commodo, posuere justo eu, mollis tortor. Nunc at sollicitudin lorem. Vestibulum lobortis et dolor quis commodo."
				+ "Praesent convallis est in risus pharetra, eu viverra risus feugiat. Fusce congue est vitae feugiat pharetra. Morbi non est ac ante vehicula congue at id metus. Ut bibendum ligula neque, id imperdiet nisi varius eget. Phasellus eget erat eu lectus iaculis pellentesque sit amet suscipit sem. Morbi nunc risus, pharetra id risus semper, posuere vehicula urna. Duis congue velit a quam dignissim, ut vehicula orci pulvinar. Vivamus libero purus, consequat quis bibendum vel, faucibus id ante."
				+ "Fusce eget lorem quis enim tempor egestas. Curabitur tristique faucibus orci in pellentesque. Suspendisse sed ex tempus, bibendum quam a, venenatis mi. Sed aliquet dapibus purus vitae ornare. Vivamus massa sapien, varius at pretium quis, tempus sed nulla. Phasellus iaculis tempus accumsan. Morbi scelerisque ligula a lacus pretium mattis. Etiam et dignissim neque. Ut nisl enim, egestas ut commodo porta, pharetra et libero. Nulla suscipit libero vel nunc euismod, id laoreet velit viverra. Suspendisse sed mauris eget eros facilisis cursus. Nam aliquam maximus porttitor. Integer eu ornare ipsum, id fermentum diam."
				+ "Phasellus pulvinar dui quam, aliquet faucibus odio tristique ac. Quisque mattis maximus augue a rutrum. Donec non justo at est consequat rhoncus posuere egestas ligula. Vestibulum venenatis imperdiet lorem, ut pellentesque urna semper eu. Etiam aliquet urna tincidunt dui rhoncus blandit. Phasellus a ipsum diam. Suspendisse felis massa, efficitur dictum diam a, dignissim hendrerit ligula. Ut mollis mattis laoreet. Nunc sit amet tincidunt libero, ac suscipit purus. Duis odio mauris, iaculis vel hendrerit a, dapibus at mi. Praesent lacus erat, consequat sed faucibus eget, aliquet lacinia lorem. Phasellus sed erat diam. Nam ut mauris et arcu congue ultricies ut et magna."
				+ "Integer a mi pharetra mauris condimentum tristique. Aliquam blandit, diam in elementum interdum, magna nibh tincidunt leo, nec lacinia quam nunc sit amet metus. Quisque ut odio risus. Quisque malesuada auctor sapien, sed malesuada arcu condimentum vel. Aliquam nec arcu ipsum. Sed vel porttitor felis. Nulla pretium metus eu fermentum tincidunt. Sed venenatis sem non vulputate gravida. Nam enim leo, pretium non vulputate laoreet, sollicitudin ac justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada imperdiet vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum rhoncus ipsum a velit varius, sit amet interdum quam consectetur. Etiam vitae placerat est. Vestibulum eget maximus erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
				+ "Etiam interdum, erat vel lacinia vehicula, quam tortor ullamcorper massa, nec suscipit tellus sem quis sapien. Proin feugiat ante ac condimentum pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed lacinia, tellus vitae malesuada feugiat, leo nibh pellentesque lorem, nec mollis libero odio vitae felis. Nam sit amet ipsum hendrerit, imperdiet ligula in, vestibulum metus. Curabitur nisi sapien, bibendum id commodo eu, tincidunt ut massa. Phasellus egestas eros vitae blandit rutrum. Morbi mollis ultrices pulvinar. Praesent nulla risus, semper eu augue eu.";
		
		String texto2000Palavras =
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque congue augue vitae ultrices lacinia. Donec mauris tortor, molestie varius nulla vel, volutpat suscipit sapien. Vestibulum tempus velit vitae est gravida dignissim. Proin interdum dolor nisl, sed hendrerit lectus finibus sit amet. Quisque vel lectus vitae neque aliquet facilisis. Nulla posuere imperdiet felis, quis aliquet sapien bibendum quis. Proin quam sem, maximus vitae accumsan id, convallis a nisi. Nullam viverra iaculis finibus. Nullam placerat est turpis, at bibendum ante porta at. Aenean eu pharetra sem."
				+ "Fusce sollicitudin porta sapien, sed maximus dui lacinia in. Phasellus fermentum pulvinar felis, et ultricies sapien mattis vel. In ut purus nec ligula aliquet maximus. Sed fermentum massa vel aliquam placerat. In consectetur pulvinar viverra. Fusce convallis, purus non auctor consectetur, erat dui sagittis ante, eget convallis diam risus elementum lectus. Mauris eget neque semper tellus condimentum molestie. Etiam accumsan augue vel dui maximus consequat."
				+ "Fusce quis lacus consequat, semper risus ac, consectetur lorem. Aliquam vitae libero diam. Vestibulum ullamcorper augue ut augue placerat, eu blandit lectus egestas. In porttitor vestibulum velit a elementum. Morbi non lacus vitae est consequat venenatis in a augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vel sollicitudin massa. Curabitur ligula dui, faucibus sit amet nunc quis, aliquet pharetra mauris. Nunc a ante condimentum, porttitor ante vel, tristique erat."
				+ "Fusce a diam feugiat, luctus massa quis, vehicula tortor. In convallis, metus id ullamcorper ornare, dui arcu euismod sem, nec egestas lorem ligula sit amet ante. Maecenas tempus odio eu magna feugiat, sed scelerisque est gravida. Etiam quam nisl, congue id mollis sit amet, dignissim non odio. Fusce pharetra sem ut augue interdum, nec blandit magna lobortis. Nullam porttitor urna justo, sed facilisis eros laoreet ut. Sed mollis porta leo, dignissim mollis purus sodales eget. Suspendisse a suscipit odio. Praesent metus est, laoreet non eleifend eu, dapibus sed lectus."
				+ "In consectetur sollicitudin velit ac lobortis. Suspendisse aliquam ipsum non nisi ultricies, in malesuada est fringilla. Proin vel eros et erat rutrum rutrum id eget odio. Suspendisse quis augue a mi semper tristique nec et metus. Aliquam feugiat ultrices velit, eget sodales odio. Nulla suscipit turpis augue, nec mollis dolor blandit quis. Aenean maximus ac nisl quis porttitor. Donec egestas sem gravida sem convallis placerat. Aliquam et euismod eros. Aliquam sed porttitor nulla. In neque eros, euismod in nulla a, feugiat malesuada nisl. Proin efficitur arcu nec varius maximus. Donec ut fringilla mi."
				+ "Fusce auctor rhoncus nisi. Sed euismod fringilla velit, at feugiat mauris hendrerit sed. Proin semper vehicula eleifend. Suspendisse euismod, tellus et tempor lacinia, urna ipsum facilisis tortor, a convallis sapien mi eu felis. Praesent vulputate dui id volutpat volutpat. Suspendisse luctus faucibus turpis, eget efficitur sem. Ut faucibus tincidunt dui, id malesuada sapien tristique a. Quisque et consectetur urna. Phasellus interdum velit sed elit tincidunt sollicitudin. Aliquam eros mauris, pellentesque vel orci ac, placerat efficitur est. Vestibulum eget ultrices magna. Nam scelerisque malesuada purus, dignissim fermentum sem rutrum ut."
				+ "Phasellus malesuada dignissim eros eget viverra. Duis facilisis at purus non consectetur. Donec tristique massa sed mauris gravida, a facilisis magna rutrum. Nulla tortor augue, maximus ut massa a, dignissim feugiat arcu. Curabitur nec dolor eu massa mattis facilisis. Mauris congue lacus quis risus sollicitudin sollicitudin. Etiam vel elit at magna placerat tincidunt."
				+ "Donec a bibendum sem, volutpat consequat lacus. Nulla sagittis sed enim ut finibus. Nunc tincidunt diam magna, quis consectetur lectus vestibulum vel. Donec non euismod ex. Phasellus auctor velit mi. Nulla porttitor dolor a justo posuere commodo. Sed tempor tincidunt elit. Maecenas lacinia porta eros ac molestie. Pellentesque ac efficitur magna. Donec eget dictum dolor, nec feugiat lorem."
				+ "Nulla malesuada ante sed nibh feugiat, id cursus leo tincidunt. Quisque justo dolor, malesuada in tellus blandit, viverra sodales nibh. Sed eu aliquet lorem. Morbi bibendum, leo in blandit sollicitudin, felis eros tristique quam, ut gravida velit elit id leo. Donec et nunc in tortor efficitur euismod vel vitae dui. Sed consectetur at neque in faucibus. Etiam eu mauris eget orci convallis viverra. Donec suscipit erat eget felis malesuada, ut facilisis erat placerat."
				+ "Sed vel leo euismod, sagittis lorem quis, sollicitudin justo. Mauris pulvinar vitae nulla quis cursus. Nulla rutrum sodales sem, quis finibus lectus tincidunt ac. Suspendisse tempor massa id purus hendrerit, sit amet aliquam diam pharetra. Pellentesque tortor massa, tempus quis nulla ac, ullamcorper egestas mi. Morbi mollis nunc in vehicula faucibus. Pellentesque in pharetra neque, at pharetra ipsum."
				+ "Mauris turpis tortor, vehicula et justo vel, scelerisque accumsan lorem. Vestibulum tincidunt felis non tellus luctus commodo. Curabitur eu odio quis lacus interdum viverra. Aenean ultricies dictum elit elementum suscipit. Sed quis nisi ac metus gravida mollis. Maecenas egestas turpis a libero fermentum ullamcorper. Cras ullamcorper diam ac enim lacinia condimentum. Donec ac lobortis dui, eget finibus nibh. Ut molestie viverra accumsan. Cras mattis dolor vel massa placerat, nec porttitor tellus sodales. Maecenas vel nulla nisi. Mauris eu dui efficitur, commodo purus finibus, volutpat magna. Ut at egestas mauris, id imperdiet urna. Duis eleifend non nibh a tempor. Sed quis diam ut nisl imperdiet fringilla."
				+ "Integer vitae ligula purus. Curabitur convallis, massa nec blandit pretium, ante enim iaculis lectus, vel aliquam mauris neque iaculis ante. Praesent diam ante, efficitur quis convallis vitae, accumsan vel dolor. Ut aliquet purus ut auctor commodo. Etiam at lectus eu magna tempor aliquet. Fusce varius, augue in congue elementum, diam lectus blandit eros, at accumsan mi justo et mauris. Nunc nibh quam, finibus eu hendrerit sed, condimentum et urna. Etiam sit amet quam ac velit tempus semper eu id quam. Nulla nisi justo, tincidunt eu luctus et, molestie eu ante. Proin volutpat, magna non sagittis accumsan, massa mauris bibendum felis, ut consectetur diam justo ut odio. Fusce dolor leo, scelerisque eget nibh sit amet, condimentum mattis eros. Phasellus euismod dignissim porttitor. Sed rhoncus mauris a dui pellentesque, in lacinia turpis suscipit. In posuere, orci dictum pharetra maximus, massa nunc elementum magna, nec aliquet orci ex sed risus."
				+ "Morbi a pretium risus. Proin hendrerit ut neque vitae suscipit. Donec urna lectus, porta id accumsan a, vehicula dictum augue. Sed quis lobortis nibh. Sed consequat mi id ipsum volutpat, non gravida massa scelerisque. Suspendisse quis lacinia lectus, sit amet consectetur nisl. Praesent venenatis hendrerit sollicitudin. Sed odio libero, ultrices sit amet fermentum et, tincidunt at ipsum. Etiam volutpat magna in risus tincidunt dapibus. Nam a lorem nec mi mollis tincidunt ac et dui. Aliquam sodales, urna in convallis dapibus, tortor risus rhoncus magna, ut sodales enim dolor commodo dui. Suspendisse condimentum mauris ante, vitae molestie mauris porttitor et. In dignissim justo vehicula porta ultrices. Suspendisse viverra gravida ultrices. Suspendisse ut facilisis dui."
				+ "Donec tempor elit et enim consectetur, eget tempor nisi lacinia. Aliquam quis ultricies neque, nec scelerisque diam. Aliquam eget nunc nec sem scelerisque elementum. Cras venenatis imperdiet diam in consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vestibulum nunc sed odio fermentum varius eu sed sapien. Mauris accumsan lacinia elementum. Sed consectetur nisl sit amet vestibulum auctor. Proin tempus, magna sed dignissim blandit, eros mi luctus purus, in vestibulum orci tellus ut mi."
				+ "Duis convallis at dolor ut cursus. Sed dolor erat, semper id risus vel, pharetra tempor mauris. Aenean quam eros, condimentum tincidunt dolor vitae, sodales rhoncus neque. Nam tempor ut tellus vel convallis. Nam tempus diam in ex consectetur ultricies. Nunc sit amet ultricies odio. Nullam eleifend eleifend gravida. Morbi tortor magna, molestie ac feugiat in, venenatis ac nulla. Duis a faucibus augue."
				+ "Quisque gravida dictum orci non ornare. Pellentesque congue, purus ac gravida vulputate, massa nibh tempor mauris, quis malesuada velit sem a metus. Cras semper velit eu mi varius consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris sit amet lacus malesuada, ultrices diam et, euismod nisi. Cras sed elementum tellus, sit amet rhoncus felis. Praesent lectus augue, fermentum id ultrices vitae, posuere ut arcu. Praesent convallis dignissim nibh. Cras neque augue, lacinia eget ex nec, posuere condimentum risus. In nec finibus ipsum. Proin ac dictum turpis. Ut mollis eros ac condimentum pharetra."
				+ "Ut condimentum ex dolor, sed faucibus ante euismod at. Nunc tempor nisi ligula, sed pellentesque enim iaculis sodales. Sed viverra mi non commodo vestibulum. Nam sed arcu a leo suscipit finibus a sed mauris. Duis porttitor nisi nec accumsan tincidunt. Nunc vestibulum lobortis ornare. Maecenas vulputate, purus eget cursus porttitor, leo odio porttitor erat, porta ornare ligula ipsum non tellus. Ut cursus posuere consequat. Donec odio neque, malesuada congue vulputate a, posuere in justo. Nulla facilisi. Maecenas sem velit, elementum ut gravida quis, varius vel nibh. Ut pellentesque lectus urna, sed laoreet felis accumsan eu. Maecenas eu blandit mauris. Sed tempor ligula sit amet eros laoreet, non porta velit gravida."
				+ "Nunc interdum in erat ut consequat. Duis vitae enim ut ipsum condimentum tincidunt. Duis eget dolor sed nisl ultricies dignissim. Pellentesque hendrerit diam lobortis, tincidunt quam nec, sodales mauris. Integer maximus tristique erat, molestie semper mauris sodales et. Aenean ex mauris, accumsan nec tristique non, porttitor ac sem. Mauris efficitur elit quis risus porta, eget ultrices nunc iaculis. Ut ornare ligula luctus dictum varius."
				+ "Nullam maximus at risus eget rhoncus. Nulla vitae nisl a lorem luctus volutpat. Vivamus dapibus aliquam nisl id venenatis. Vivamus sed tortor ex. Duis vel ligula vestibulum, auctor urna eu, pretium ipsum. Cras blandit mi lacus, nec mattis magna rhoncus sit amet. Maecenas lobortis erat ac luctus efficitur. In mauris nisl, ullamcorper eu nisi vitae, mollis pretium eros. Vestibulum ultricies ante a quam egestas, eu volutpat elit egestas. Praesent ut ornare lacus. Curabitur porta ac leo et consequat. Fusce lectus risus, molestie id placerat vitae, mattis quis purus. Ut fringilla pharetra purus, cursus congue nisi. Nam scelerisque ipsum posuere, volutpat ligula eget, commodo tortor. Nulla blandit ultrices maximus. Duis a ligula felis."
				+ "Suspendisse mattis leo sit amet efficitur lacinia. Phasellus mollis pharetra purus iaculis commodo. Vestibulum lacinia interdum lacus, nec porta est dictum vitae. Donec consectetur convallis purus, vitae varius justo viverra iaculis. Vestibulum non facilisis purus. Nulla scelerisque commodo sollicitudin. Aliquam magna libero, vulputate ut arcu vulputate, dictum laoreet ex. Nunc in placerat lorem. Suspendisse pharetra augue nec dui malesuada, efficitur sodales sapien gravida. Curabitur elementum in nulla nec dictum."
				+ "Donec gravida enim ipsum, ut porttitor augue maximus vitae. Nullam et lectus eget elit facilisis porttitor. Suspendisse vel magna ac enim consectetur ultricies. In maximus sapien nec lectus molestie ornare. Curabitur ut varius arcu. Vivamus sed nisl ac dui mattis mollis. Nunc bibendum fringilla bibendum."
				+ "Vivamus ut erat id urna varius consectetur in a arcu. Nunc et sapien augue. Curabitur libero leo, consectetur vitae massa non, iaculis euismod sapien. Ut dignissim, lacus eu porttitor imperdiet, arcu neque semper ex, ut varius augue leo nec magna. Praesent placerat ante vitae nunc facilisis accumsan. Maecenas feugiat pellentesque mauris at iaculis. Integer scelerisque orci velit, quis pulvinar augue fringilla eget. Suspendisse enim ligula, ultrices ac velit at, luctus vulputate est. Phasellus a orci vitae eros tincidunt lacinia dignissim non neque. Nam ligula quam, fermentum vel justo sed, condimentum hendrerit magna. Fusce tempus tempor dolor, at mattis nunc porttitor at. Aliquam pretium nisi odio, vel efficitur lorem porta a. Proin ut augue et mauris lacinia facilisis."
				+ "Mauris convallis ex ac elit ornare, nec sagittis ante commodo. Vestibulum pulvinar mauris sem, et ultrices lectus accumsan dignissim. Integer non cursus eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ultrices erat in varius bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida justo nisi, quis bibendum purus elementum vel. Praesent posuere, tellus eget pretium congue, arcu turpis pellentesque augue, eget ultricies lorem purus et risus."
				+ "Vivamus vestibulum mauris malesuada, fermentum sapien et, posuere nisl. Mauris cursus porta pulvinar. Fusce eget magna non tellus mattis finibus. Integer finibus turpis in sem commodo, non posuere est consequat. Donec sed nulla eros. Proin bibendum elementum est, in eleifend ex. Nunc nec turpis et magna rhoncus convallis auctor euismod purus. Proin ullamcorper enim id diam rutrum, rhoncus bibendum nisi tincidunt. Integer interdum sem eu lectus dictum, et interdum nibh hendrerit. Nullam in vehicula.";
		
		String texto5000Palavras = 
				"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel tincidunt purus, in ornare justo. Nulla facilisi. Proin elementum id libero vel egestas. Nam in volutpat elit. Ut eget aliquam turpis. Donec tempus sagittis nunc sit amet ullamcorper. Curabitur sit amet pharetra neque. Etiam augue purus, lacinia non libero et, fringilla convallis magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."
				+ "Nam congue metus eget mauris mollis tempus. In hac habitasse platea dictumst. Suspendisse nec accumsan turpis. Pellentesque sollicitudin maximus felis, non scelerisque erat volutpat nec. Phasellus nec ligula enim. Sed facilisis odio mi, efficitur tempus libero tristique quis. Mauris at eros at orci finibus posuere sit amet et lorem. Sed vel neque ipsum. Nullam non dignissim ipsum, ac pretium tortor. Nullam sagittis dolor luctus dolor laoreet tincidunt. Duis in tempus sapien. Curabitur sem orci, ultrices ac facilisis vel, malesuada eget urna."
				+ "Morbi a quam at ligula consectetur malesuada. Vestibulum sit amet ante quis ipsum viverra malesuada vel eu ex. Pellentesque condimentum diam ac nisi feugiat viverra. In quis felis turpis. Suspendisse pulvinar nibh vitae congue blandit. Praesent varius metus in dictum egestas. Nunc rutrum, nisl sit amet feugiat porttitor, mauris metus tristique ante, sit amet commodo lorem sapien sit amet est. In a malesuada nisi. Cras pharetra lectus a feugiat mollis. Praesent eu ipsum urna. Praesent ut justo erat. Sed ac porttitor diam, sed egestas mi."
				+ "Nam sed lorem diam. Aenean maximus non urna sit amet tempus. Sed quis massa eu erat accumsan egestas. Fusce at aliquet justo. Duis porttitor interdum metus, sed rhoncus mi consectetur a. Donec vel dolor eros. Donec eu libero ac dui iaculis consectetur. Donec scelerisque dui eget risus tincidunt laoreet. Nunc faucibus magna at mi dapibus commodo. Aliquam bibendum volutpat purus, nec laoreet leo sollicitudin eget. Nullam non velit lectus. Fusce pretium mi dictum enim fringilla gravida. Fusce pretium sodales elit, eget blandit erat interdum sit amet."
				+ "Phasellus pharetra nulla metus, sed aliquet lectus convallis feugiat. Nunc lorem dolor, pulvinar in bibendum eget, rhoncus non sem. Donec et consequat est. Phasellus eu tellus vel ante sodales mattis ut at eros. Nulla porttitor ut velit quis tempor. Nunc cursus dolor vel dui hendrerit consectetur. In hac habitasse platea dictumst. Aliquam venenatis a erat quis consequat. Mauris ut posuere leo. Quisque non justo dignissim, efficitur turpis vitae, finibus eros. Nullam ac sem ipsum."
				+ "Nullam efficitur ligula sapien, id commodo diam lacinia ultricies. Nam non tortor ornare, ultrices arcu id, venenatis odio. Aenean pharetra tristique euismod. Proin sodales orci ac ultricies feugiat. Vestibulum eu odio non orci hendrerit luctus. Suspendisse nec suscipit leo. Nunc vel risus turpis. Praesent eros nulla, molestie in iaculis in, pretium a tortor. Morbi sit amet ex rutrum, molestie ex ac, facilisis massa."
				+ "Mauris mattis est eget libero lacinia, a finibus lacus pellentesque. Proin metus turpis, dignissim in dictum quis, maximus quis nibh. Donec consectetur, eros vel suscipit pharetra, leo massa maximus lorem, eget faucibus sem orci malesuada metus. Proin luctus vestibulum odio non tempus. Morbi sed sapien tortor. Sed mi massa, egestas bibendum facilisis sed, dapibus vel sem. Sed lacinia tempor lacus, id rhoncus sapien mollis eu. Fusce interdum sit amet leo ut placerat. Vivamus eget tempus urna, sed accumsan sapien. Nunc congue, ex auctor consequat facilisis, velit eros bibendum elit, ut varius orci augue bibendum sapien. Ut interdum lectus quis felis finibus dapibus. Maecenas sed ante eu libero facilisis euismod eu ut dui. Aliquam luctus dui id nulla iaculis, id ultricies eros commodo. Maecenas lacinia mi accumsan dui scelerisque, sit amet posuere dolor aliquam."
				+ "Integer rutrum gravida leo. Cras sodales porta maximus. Maecenas malesuada, nisi a mattis ullamcorper, felis mi suscipit tellus, gravida eleifend nibh turpis et augue. Nullam eu tellus dictum, porta ipsum vel, vestibulum tellus. Curabitur viverra nibh ut malesuada ornare. Aliquam ultricies accumsan magna eu volutpat. Nullam sodales vulputate metus, accumsan commodo nulla luctus id. Sed sollicitudin, arcu et aliquet sodales, leo enim vestibulum justo, sit amet rhoncus lacus arcu ac elit. Nunc ullamcorper, tellus bibendum rutrum posuere, diam lorem sagittis turpis, aliquam aliquet lacus lorem non orci."
				+ "Nam gravida volutpat sagittis. Ut ut ligula quis nibh gravida maximus. Morbi sed venenatis enim, sed sodales ipsum. Quisque luctus lacus accumsan aliquam venenatis. Curabitur nec fermentum ante, sed accumsan ligula. Ut sem quam, condimentum id efficitur ut, finibus id lacus. Sed sollicitudin libero et lorem semper, vel egestas urna blandit."
				+ "Vivamus semper orci vitae diam porta, posuere cursus velit viverra. Nam auctor enim eget purus congue fermentum vitae vel massa. Nullam bibendum ullamcorper turpis a bibendum. Suspendisse aliquam eget magna non semper. Nunc euismod finibus metus eu rutrum. Integer rhoncus dui placerat ex rhoncus auctor. Suspendisse potenti. In convallis vestibulum sodales. Nunc ut enim ultricies, ullamcorper eros sed, molestie augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus malesuada interdum lacus in mollis. Nullam porta viverra purus sed aliquet. Praesent sit amet porta neque. Morbi condimentum dictum sapien nec dictum. Nunc dictum est nec pretium vestibulum. Sed blandit, dolor non venenatis varius, quam nulla ullamcorper nunc, non egestas tellus quam a diam."
				+ "Proin maximus dui sit amet augue iaculis lacinia. Mauris nunc mauris, placerat quis elit at, malesuada varius libero. Donec placerat posuere dolor, sed consequat mauris lobortis at. Sed justo arcu, pulvinar a nibh eu, gravida iaculis libero. Pellentesque leo dolor, vehicula vel velit sed, interdum tincidunt turpis. Suspendisse potenti. Praesent sagittis quam volutpat, accumsan libero quis, luctus urna. Sed ac aliquet est. Aliquam cursus augue tellus, non posuere nisi iaculis eu. Nulla malesuada nisl semper tortor condimentum, sed lobortis magna gravida. Nulla ut ornare enim. Donec vulputate et mi ac faucibus. Duis ut erat eu urna ornare vestibulum aliquam at lorem."
				+ "Aenean nec justo nec elit porta posuere sit amet vitae orci. Vivamus eget tempor sem, at accumsan dui. Nunc mi velit, auctor id placerat vitae, ornare suscipit tellus. Nulla facilisis enim placerat felis pretium luctus. Sed rutrum, felis a rutrum suscipit, urna neque placerat dolor, eu iaculis elit turpis id dolor. Aliquam sodales quis neque ac tristique. Morbi fermentum, mi et mollis varius, nulla risus semper urna, vitae feugiat erat enim in turpis. Suspendisse vel nulla ullamcorper, suscipit urna id, commodo ipsum. Nunc quam orci, finibus id nulla non, posuere luctus purus. Phasellus mattis convallis ex non dignissim."
				+ "Quisque rutrum hendrerit ipsum a iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla facilisi. Proin lacinia maximus augue non varius. Praesent venenatis condimentum fermentum. Integer lacinia non nulla quis commodo. Proin ornare ante quis viverra hendrerit. Nulla facilisi."
				+ "Integer sodales nisl id elementum consectetur. Donec commodo lectus id tincidunt aliquam. Sed nisl mi, porta in dui id, porta pulvinar elit. Curabitur ac egestas erat. Vivamus pharetra a sem eu euismod. Nunc iaculis, mauris pellentesque suscipit auctor, ante urna dignissim massa, maximus efficitur libero dolor non nisi. Vivamus laoreet convallis vehicula. Cras a sodales orci, et pulvinar odio. Nullam quis tempus orci, a lacinia sem. Nulla posuere lectus ac lorem imperdiet, sit amet pulvinar justo hendrerit. Ut dui tortor, commodo eget gravida eu, bibendum sed urna. Donec gravida, ipsum sed aliquet maximus, purus nunc vulputate magna, non egestas ante magna in tortor. Etiam interdum tortor sit amet diam vehicula finibus ut at ante. Sed tincidunt condimentum metus vel porttitor. Vestibulum eget tristique tellus, id aliquam sem."
				+ "Sed quis lacus fringilla, semper orci ac, efficitur turpis. Nulla facilisi. Vestibulum vel semper massa. Praesent mattis quam vel commodo mollis. Nulla nibh nisi, cursus at sodales nec, iaculis efficitur mi. Nunc mollis efficitur nibh ac volutpat. Proin vehicula semper turpis, a tincidunt est ultricies sit amet. Nam pulvinar, nisi eget placerat rhoncus, ante lectus iaculis nibh, vitae aliquam felis purus luctus augue. Curabitur elit justo, viverra id ipsum non, consequat posuere neque. In hac habitasse platea dictumst."
				+ "Vivamus porta tortor porttitor tincidunt iaculis. In scelerisque urna eu porttitor posuere. In maximus augue id tellus semper, vel semper mi posuere. Nunc eros nibh, ultricies eu sapien et, scelerisque porta turpis. Duis vehicula, nisi eget consequat lobortis, turpis ex sodales felis, sed lobortis massa risus non risus. Maecenas nec lacus vitae dui pharetra tincidunt. Aliquam eget porta turpis. Donec dapibus nulla gravida ante tincidunt, dictum egestas sapien interdum."
				+ "Integer fringilla nisi orci, quis interdum dolor euismod eget. Ut at ultrices libero. Sed cursus bibendum venenatis. Praesent eget vulputate sem. Proin vulputate lobortis pellentesque. Integer rutrum odio non arcu tincidunt, sit amet gravida mi posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."
				+ "Nullam finibus bibendum urna, sed semper magna tempus eu. Etiam sollicitudin dictum eros, consequat tempus sem rutrum quis. Vivamus dictum diam est, vel gravida diam commodo quis. Aenean auctor semper elit ac vulputate. Cras iaculis varius nisl sit amet dapibus. Ut aliquet nibh lectus, id interdum risus aliquam id. Nunc turpis tortor, aliquet ac libero quis, ornare ullamcorper ante. Praesent est libero, molestie eu nulla ac, malesuada vehicula nisi. Sed sed ornare velit, ac dictum magna. Phasellus placerat vel erat sit amet tempus."
				+ "Pellentesque scelerisque, velit eget luctus commodo, lorem urna luctus felis, et luctus augue elit eget enim. Fusce sit amet libero sit amet lorem egestas euismod et eu lorem. Nulla faucibus pretium convallis. Donec eu libero purus. Sed non risus at lectus lacinia tincidunt et id tortor. Cras volutpat a sem id posuere. Nulla id sollicitudin ante. Phasellus semper lacus nec urna pellentesque, vitae tincidunt arcu aliquam. Curabitur malesuada elit eu leo finibus, ac laoreet ante vehicula. In ullamcorper vitae augue vel iaculis."
				+ "Curabitur quis massa at mi feugiat volutpat. In quis mollis metus, eget auctor nisl. Vestibulum condimentum posuere risus, non varius neque mollis eu. Nulla facilisi. Ut ac semper odio. Vivamus porttitor turpis eget enim tincidunt, eu laoreet ante iaculis. Phasellus tellus risus, fermentum sit amet ex in, pretium ultricies orci. Quisque placerat, tellus nec mattis sollicitudin, sem ligula congue nunc, a fermentum ex tellus et diam. Vestibulum vitae tempus mi, vel maximus sapien. Morbi turpis ante, tempor eu semper et, ultricies eu diam. In ut felis maximus neque fermentum dictum."
				+ "Integer bibendum laoreet mauris ac consequat. Proin a sodales tortor. Nullam sed nulla in dolor vulputate iaculis. In sagittis arcu mauris, ut viverra massa aliquam a. Fusce ut porttitor libero, in dictum nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ut neque massa. Mauris ac magna nec ante convallis faucibus. Nullam ornare felis nunc, ac tincidunt mauris consectetur in. Nam accumsan ipsum vitae ligula pharetra, nec aliquet ex vestibulum. Etiam elit mi, tristique in elit non, tincidunt luctus orci. Proin quis velit id urna ornare consequat sed ac odio. In turpis orci, feugiat id turpis eu, volutpat gravida magna. Nulla non nulla et enim fringilla mollis sit amet sed mauris. In pellentesque suscipit ultrices."
				+ "Nam id est pharetra, sagittis eros at, vehicula arcu. Curabitur quis dolor sagittis, maximus eros quis, dapibus purus. Donec ac aliquet diam. Suspendisse vel pharetra orci, suscipit suscipit ante. Donec ultricies sem at varius tincidunt. Ut quam massa, ultricies nec leo et, egestas sagittis nunc. Donec non venenatis neque, ut commodo urna. Praesent ut est sit amet enim interdum maximus. Suspendisse vitae dui ut ex vestibulum sollicitudin."
				+ "Curabitur neque turpis, tristique eu nulla ut, luctus volutpat libero. Morbi quis est eu risus tincidunt vestibulum in at dui. Pellentesque efficitur lacinia libero, non cursus turpis commodo at. Vestibulum non augue a neque tincidunt facilisis. Phasellus placerat, elit vel porttitor pharetra, mi mauris sagittis ex, vel rutrum nisl lacus vitae lorem. Integer condimentum tempus libero, quis luctus ex sagittis sit amet. Suspendisse orci massa, molestie in augue mattis, placerat finibus nunc. Phasellus a nulla vehicula, ornare nunc sit amet, pulvinar lacus. Phasellus tempor lectus in maximus mollis. Cras ornare consequat orci sed hendrerit. Phasellus et vehicula dui. In luctus ipsum ut lorem mattis tristique. Nulla facilisi. Suspendisse finibus finibus orci, vitae ullamcorper orci tincidunt eu. Nunc in venenatis felis. Phasellus nec ipsum quis sem malesuada iaculis."
				+ "Cras eu felis libero. Nullam at justo ut felis euismod auctor. Pellentesque cursus purus quis nunc auctor, sed ornare nisi semper. Curabitur tempor iaculis ullamcorper. Nulla finibus consectetur lorem, sed condimentum felis facilisis vel. Praesent ac justo ullamcorper, dignissim erat vitae, iaculis ante. Vivamus vel augue in metus fringilla aliquet et nec dui."
				+ "Phasellus placerat accumsan placerat. Ut id sodales diam. Vivamus libero nulla, volutpat non maximus non, ultrices at risus. Aliquam eget consectetur mauris, in interdum tellus. Fusce urna nibh, aliquet ac ante non, tincidunt viverra ligula. Nunc egestas, nisi nec porta suscipit, nisl mauris maximus purus, sit amet ornare erat nibh ut purus. Nulla dapibus nulla eu hendrerit aliquam. Maecenas ut eleifend diam. Fusce ullamcorper nisi quam, quis mollis dui aliquam vitae. Curabitur eleifend condimentum posuere. Curabitur ac accumsan velit, in viverra mi. Morbi finibus et libero vitae tincidunt. Phasellus leo ex, mattis ut tristique a, bibendum at risus. Aenean id felis risus. Etiam quis magna enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit."
				+ "Duis viverra pretium congue. Quisque vel commodo metus. Duis ut venenatis tellus. Maecenas in mollis tortor. Ut sed ex blandit, iaculis augue vitae, faucibus orci. Quisque at sapien eu tellus semper porttitor. Etiam faucibus nulla neque, ut mattis augue vulputate ultrices. Aliquam sodales eu libero quis porttitor. Quisque laoreet non sapien at laoreet. Integer nec quam libero."
				+ "Sed suscipit mi ullamcorper malesuada condimentum. Nulla eu elementum augue. Nunc quis tincidunt eros, eu feugiat tellus. Donec malesuada nisi ligula, vel vestibulum ex cursus at. Nulla tincidunt vel leo eu porta. Curabitur sit amet maximus nisi, a fermentum nisl. Proin elementum vehicula nunc ut scelerisque. Sed fermentum posuere lobortis. Vestibulum at placerat risus. Curabitur nec ullamcorper sem, eget sodales tellus. Aenean lacinia lobortis purus, consectetur blandit nulla pulvinar vitae."
				+ "Nullam porttitor lectus ac porta porta. Integer justo metus, bibendum finibus neque quis, sollicitudin porttitor justo. Suspendisse arcu libero, tristique quis luctus sit amet, malesuada eget lectus. In lorem sem, convallis at dui ut, pharetra pharetra mauris. Suspendisse sagittis, ante quis lobortis feugiat, risus tortor sodales tellus, at vestibulum purus turpis eget lorem. Fusce justo felis, blandit non pulvinar at, dictum a felis. Nulla elementum, sem in lobortis tristique, magna ipsum commodo massa, a pharetra orci leo in elit."
				+ "Fusce ac elit dictum, sagittis lectus quis, sodales est. Cras eget hendrerit eros, quis maximus purus. Etiam blandit fringilla urna at fringilla. Vivamus non lacus vel nulla tristique ullamcorper. Maecenas rhoncus quis quam eget semper. Nulla quis elit at arcu accumsan vestibulum at nec velit. Fusce dignissim lectus ut felis pellentesque tristique. Praesent sit amet tortor rutrum, interdum mi quis, ornare elit. Phasellus condimentum tristique diam, tincidunt elementum sem ultrices in. Cras non pretium massa, id convallis nisi. Proin hendrerit massa vitae magna commodo, eu ultrices lectus porttitor."
				+ "Vestibulum faucibus orci in velit consectetur, in convallis nulla viverra. Maecenas eu nisi mi. Donec eget dolor erat. Donec lacinia, odio ut egestas tempor, ex augue ultrices quam, ut pharetra velit mi at mauris. Nulla sollicitudin dignissim pharetra. Mauris maximus, nibh a tincidunt pulvinar, ligula dolor sollicitudin mauris, nec volutpat nibh nisl ac massa. In hac habitasse platea dictumst. Aliquam vulputate, est quis bibendum molestie, quam mi ultrices eros, nec rutrum libero tellus sit amet mauris. Pellentesque euismod ultrices mi sit amet dignissim. Morbi gravida tristique lorem eget molestie. Maecenas porttitor magna quis nulla hendrerit pulvinar."
				+ "Proin viverra lorem id nibh eleifend, cursus scelerisque velit pulvinar. Nullam congue aliquam sem, a malesuada nisl scelerisque sed. Integer blandit hendrerit felis, eu feugiat mauris faucibus et. Nunc at vulputate mauris, non finibus arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam purus sem, commodo vel ligula non, commodo scelerisque nunc. Donec tempus felis in enim vestibulum, ut consequat ligula maximus. Ut eget tincidunt odio, id sagittis nunc."
				+ "Nam bibendum nulla mauris, non ultricies erat scelerisque in. Aliquam sollicitudin, est quis tempor tempus, sem velit fringilla leo, in rhoncus nisi ligula ut nisi. Quisque sapien orci, bibendum nec dictum quis, dictum non ipsum. Sed elementum quis diam pretium commodo. Pellentesque eu tellus sit amet neque lobortis maximus at eu nisl. Integer et convallis odio, et pharetra justo. Duis volutpat arcu non lectus maximus condimentum. Aliquam a lacus semper, faucibus erat nec, malesuada nisl. Sed non rhoncus sapien, aliquet efficitur arcu. Sed vel ligula ut odio dictum pellentesque. Curabitur suscipit risus id nibh consequat ultrices eu eu magna. Donec laoreet ipsum non enim consectetur consectetur. Donec consectetur semper purus. Vestibulum non erat ut augue laoreet molestie eu ut risus. Cras vel nulla ut arcu blandit vestibulum in nec lacus."
				+ "Proin ut bibendum mi, non sagittis nunc. Nunc quam justo, interdum sed lorem ac, fringilla facilisis dolor. Nam at tristique quam, a semper nisi. Aenean in arcu ipsum. Fusce pulvinar felis est, vitae dictum lorem cursus vitae. Donec pretium lorem diam. Donec sagittis faucibus mauris, id iaculis neque tincidunt vel. Nullam ut quam eu ex faucibus facilisis luctus quis neque. Integer consequat urna quis urna feugiat commodo. Nullam pharetra turpis sem, vitae mollis tortor tempor vel. Nulla sed facilisis orci, vel pretium enim. Vestibulum blandit ultricies posuere. Praesent vestibulum lectus in neque blandit gravida. Vestibulum lacus neque, porta sagittis turpis in, tempor gravida orci. Sed elementum sit amet mauris et vehicula."
				+ "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non risus velit. Sed vel metus a augue pretium varius non a mauris. Pellentesque at lacus dui. Aenean quis elit tincidunt, pharetra dolor nec, varius nibh. Suspendisse potenti. Nullam ac felis a est facilisis cursus. Quisque rutrum justo ac placerat eleifend. Maecenas placerat urna euismod, feugiat arcu at, sagittis nisi. Aliquam commodo, ipsum et dictum venenatis, ex nulla gravida tellus, a hendrerit est nulla sed arcu."
				+ "Aenean blandit imperdiet quam, sit amet efficitur elit consequat a. Aliquam et metus quis ex dapibus semper. Mauris ut mi erat. Fusce a nisi eu lectus sollicitudin vehicula. Sed sollicitudin, justo ut eleifend tincidunt, sem urna luctus eros, sit amet eleifend lectus enim nec eros. Aliquam sapien enim, luctus egestas cursus at, aliquam in turpis. Phasellus vitae tincidunt ligula. Mauris et leo iaculis, pretium erat eu, dignissim ex. Curabitur eu lobortis leo. Phasellus eu condimentum massa, vitae vehicula enim. Suspendisse lobortis sem nec cursus sagittis. In dapibus tempus feugiat. Vivamus ultricies enim pharetra, rhoncus lacus a, aliquam ligula."
				+ "Quisque volutpat ultrices mi vitae sodales. Cras sit amet nunc sit amet diam pellentesque laoreet. Sed lobortis felis non quam accumsan pharetra. Nam id lobortis ante. Sed rutrum nulla felis, sit amet venenatis odio interdum nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc eget urna non neque dapibus condimentum. Proin vitae tincidunt tortor. Phasellus gravida ex ut lacinia vulputate. Suspendisse in mauris faucibus, tincidunt eros ut, cursus sapien. In hac habitasse platea dictumst. Mauris finibus risus nec nulla lacinia maximus semper in tellus. Suspendisse quam mi, viverra nec ligula sit amet, interdum pretium risus. Quisque mattis ex nec dolor malesuada, eu aliquet enim facilisis."
				+ "Nullam iaculis justo ac vulputate auctor. Ut molestie commodo rutrum. Maecenas suscipit quam a mi mollis, sit amet venenatis tellus hendrerit. Maecenas fringilla elementum nibh eget ultrices. Integer felis nulla, lacinia sit amet arcu in, convallis elementum ipsum. Donec massa neque, posuere sed auctor in, tincidunt a metus. Curabitur lacinia viverra tortor, eget efficitur orci condimentum quis."
				+ "Morbi sagittis turpis tincidunt magna placerat, non lobortis erat ornare. Praesent accumsan a enim a vulputate. Fusce turpis nunc, pretium a nisi quis, sollicitudin venenatis ex. Donec sit amet convallis turpis. Donec consequat erat at molestie pretium. Donec bibendum orci et justo dictum, sed suscipit nisi malesuada. Suspendisse at velit et ante mattis malesuada non sed enim. Vestibulum blandit enim interdum porta eleifend. Fusce ante felis, volutpat in dui non, condimentum tempus ante. Nulla facilisi. Maecenas sed est in arcu condimentum porttitor ac ac libero. Duis vitae leo non ante convallis efficitur. Suspendisse in tellus a urna consectetur vehicula finibus sagittis erat."
				+ "Nullam sit amet erat orci. Integer imperdiet bibendum mauris in mattis. Donec eu dignissim lorem, a pulvinar nunc. Mauris facilisis eros nibh, ut fermentum augue scelerisque nec. Aliquam erat volutpat. Aliquam nec pellentesque purus, a varius nisi. Suspendisse eu feugiat ligula. Fusce eget massa at ipsum viverra sagittis. Nam ac ante augue. Aenean ullamcorper convallis tellus at congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec nec magna ligula."
				+ "Duis vel nulla diam. Maecenas leo justo, tincidunt eget suscipit vitae, rhoncus ac nunc. Morbi rhoncus eros vitae leo ornare lacinia. Integer sed sapien libero. Nunc fringilla lorem eu semper posuere. Morbi aliquet facilisis orci ut scelerisque. Etiam eu ipsum vitae metus mattis aliquet. Aenean commodo consectetur aliquam. Donec imperdiet luctus mollis. Maecenas ut lobortis tellus."
				+ "Vestibulum posuere nisl id finibus dictum. Phasellus eget finibus eros. Vestibulum venenatis ligula eu congue egestas. Nulla finibus at metus quis cursus. Curabitur interdum, odio blandit ullamcorper gravida, neque tortor rhoncus nibh, id efficitur dolor tellus et odio. Vivamus at aliquet augue, ac vehicula dolor. Nunc efficitur eget ipsum quis blandit. Maecenas et pellentesque purus, eget mollis ante. Mauris libero diam, finibus vel bibendum sit amet, pretium ut est. Phasellus condimentum ultrices lorem in vulputate. Praesent ac diam et nisl feugiat fermentum id eget neque. In eget dapibus risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
				+ "Ut vel convallis felis. Sed porttitor eros sapien, non varius dolor cursus feugiat. Praesent volutpat et ligula non lobortis. Quisque dapibus lectus eget erat pulvinar, fringilla congue neque pulvinar. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi dictum felis ipsum, in scelerisque metus consequat non. Curabitur congue elementum mauris, sit amet cursus erat congue et. Mauris tempor at orci at consequat. Sed eget viverra lacus. Donec vitae lobortis sapien."
				+ "Nam quis urna vitae magna accumsan pellentesque. Curabitur felis ante, semper vitae aliquet vulputate, molestie vitae massa. Duis ac turpis hendrerit, dictum lectus nec, pretium elit. In commodo ante et diam posuere malesuada. Morbi laoreet aliquet interdum. Integer luctus, mauris sit amet cursus vehicula, enim sapien mollis orci, vulputate fermentum dui diam eget dolor. Etiam ligula mauris, consequat non cursus et, hendrerit in quam. Etiam euismod finibus mauris, quis viverra nisi rutrum sit amet."
				+ "Cras mollis nisl ac neque egestas vehicula. Aliquam in pellentesque orci. Integer vulputate, elit egestas porttitor scelerisque, elit risus congue augue, nec porta sapien metus ut enim. Integer aliquet, tortor vel blandit sodales, ante sapien suscipit nibh, eget gravida diam metus eget ex. Phasellus ornare eros sed orci tincidunt, et commodo nisl sodales. In eleifend molestie dolor, sit amet pharetra est lobortis nec. Quisque fringilla, elit id tempus sollicitudin, dolor leo faucibus arcu, sed ullamcorper massa augue quis ligula. Nam in sodales metus. Morbi sed pulvinar purus. Nullam lacus massa, congue vel feugiat et, iaculis vitae sapien. Sed condimentum urna ac massa facilisis aliquet."
				+ "Fusce tincidunt ligula orci, vel tempus dolor ultricies nec. Nam placerat lobortis nibh vitae sagittis. Donec cursus, purus id vehicula scelerisque, eros felis gravida eros, ut molestie ipsum tellus id tortor. Sed consequat id nunc ut rhoncus. Aliquam posuere, nulla vel finibus finibus, sem justo blandit ex, vel aliquam mi quam eget felis. Sed tincidunt consectetur lectus eget viverra. Morbi congue mauris nunc, nec ornare nulla sodales sit amet. Nam congue id odio eget dictum. Donec vel mauris aliquam, fermentum lacus eu, luctus metus. Nunc erat ligula, gravida sed diam in, posuere ultrices nisi. Maecenas mollis, neque nec bibendum tristique, lacus lacus gravida nisl, a sollicitudin orci augue nec orci. Aliquam et felis vestibulum, aliquam libero in, bibendum tortor. Aliquam eleifend risus a fringilla consectetur. Aliquam vel diam vitae dui vulputate fringilla. Nam elementum laoreet interdum."
				+ "Fusce dictum vitae tellus eu luctus. Cras vel metus euismod, eleifend diam eu, cursus nunc. Pellentesque eu mauris vitae velit accumsan auctor et eu nisi. Nunc vulputate neque ac nisi viverra molestie. Praesent vestibulum erat sit amet libero cursus volutpat. Sed sed eleifend massa. Mauris aliquam tristique vulputate. Ut vel nisi vel mi ultricies lobortis. Aliquam felis felis, lobortis et mi ut, mattis rutrum lorem. Etiam dignissim, ligula vel pretium porttitor, odio risus lobortis enim, nec posuere odio lacus ac ex. Suspendisse malesuada odio sed nisl vestibulum maximus. Proin non est ac quam facilisis facilisis a eget metus. Suspendisse maximus finibus pharetra. Maecenas ut condimentum massa. Donec ac sem vitae leo venenatis efficitur eu sit amet dolor. Suspendisse rhoncus dui ut ipsum interdum, at sollicitudin lectus viverra."
				+ "Curabitur non dictum risus. Praesent eget dictum enim. Phasellus consequat lacinia elit, non dapibus turpis porta rutrum. In imperdiet eget quam quis pulvinar. Nullam in augue lobortis, tempus sapien efficitur, ullamcorper ante. Aliquam facilisis auctor ante et sollicitudin. Nullam nec nisl nulla. Pellentesque id feugiat nunc. Duis gravida lectus sapien, quis fringilla ex ornare vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;"
				+ "Duis non elit nisi. Integer vel efficitur magna. Aenean turpis urna, fringilla vitae sollicitudin finibus, porttitor at neque. Vivamus maximus venenatis nulla et tempus. Fusce arcu sem, luctus quis diam vitae, condimentum eleifend diam. Mauris pretium risus in nulla semper sollicitudin. Aenean faucibus ipsum mauris, sed interdum neque egestas et. Vivamus sit amet congue libero, sit amet volutpat ligula. Nulla facilisi. Nullam et viverra quam. Aenean non dictum mi. Donec id rhoncus mauris, in mattis risus. Fusce viverra elementum diam, quis tincidunt eros ultricies vel. Sed congue mi eget vulputate luctus. Maecenas vulputate quam massa, et mollis ipsum consequat ut."
				+ "Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed turpis dui, tincidunt nec nibh et, facilisis varius risus. Fusce malesuada lectus sed massa faucibus, a ultrices risus interdum. Duis non rutrum nisi. In aliquam condimentum turpis eu viverra. Integer elementum libero vitae dapibus bibendum. Sed et erat non leo varius pellentesque quis a sem. Etiam quis posuere dolor, et pellentesque sapien. Nunc accumsan turpis vel volutpat cursus. Nulla imperdiet massa vitae varius porttitor. Proin in arcu volutpat, mattis ligula in, consectetur nibh."
				+ "Proin tempor felis a nisi blandit placerat. Proin fermentum imperdiet odio, vitae feugiat felis vestibulum in. Fusce consectetur magna urna. Sed varius lectus ipsum, eget scelerisque justo vestibulum nec. Quisque iaculis, nunc sit amet malesuada congue, nibh velit blandit lectus, eu iaculis nisl ligula eget ipsum. Suspendisse ac laoreet tortor. Sed ultricies velit quis quam semper, viverra tincidunt tortor posuere. Proin vitae erat in nibh fringilla placerat. Mauris at feugiat ipsum, nec lacinia lorem. In tincidunt eros in cursus eleifend."
				+ "Cras lacinia massa sit amet nisl sodales, sed vehicula purus vulputate. Vivamus nec tortor quis tortor tincidunt porta. Proin convallis arcu ullamcorper faucibus viverra. In dictum tristique rhoncus. Quisque varius dolor eu lectus gravida, ut suscipit dui consequat. Maecenas sit amet accumsan neque, sed ultricies justo. Quisque tempus, sem ut posuere malesuada, purus erat mollis enim, eu porttitor leo purus a mi. Suspendisse id est mollis, vulputate leo eget, pellentesque dolor. Integer sem nisl, feugiat in enim eu, gravida laoreet felis. In quis volutpat enim. Proin congue sem nulla, a luctus neque condimentum rhoncus. Cras condimentum egestas erat, eu rutrum nunc fringilla ac. Proin justo lectus, feugiat ac mattis vel, interdum vitae sapien."
				+ "Vivamus vitae purus sed sem placerat lobortis vitae a nulla. Phasellus vel ultrices urna. Curabitur sit amet dui non quam luctus venenatis. Suspendisse leo lacus, mollis sed dui ac, tristique faucibus ex. Nullam nec gravida ante. Morbi efficitur suscipit tellus, sed bibendum tellus congue vitae. Sed pulvinar eu nunc scelerisque tempus. Nulla elementum ornare tempor. Fusce ac justo orci. Sed erat felis, vulputate quis arcu sit amet, vulputate iaculis felis. Mauris non aliquet eros. Phasellus consectetur dui non ultricies gravida."
				+ "In dictum vestibulum mi. Donec pretium enim felis, in bibendum enim pulvinar in. Phasellus at felis lacus. Nam pharetra mollis ligula, quis fermentum augue pharetra eget. Nam leo orci, interdum eu erat vel, aliquet viverra mi. Pellentesque non diam at purus condimentum ornare. Pellentesque augue arcu, efficitur molestie nibh vel, luctus porttitor ipsum. Fusce et lacus pharetra, condimentum mauris id, tempus turpis. Sed ultricies ex facilisis arcu volutpat bibendum. Duis bibendum tellus mauris. Aenean rhoncus consequat dignissim. Etiam feugiat quis nisl a luctus. Morbi feugiat ante in iaculis feugiat. Nunc pellentesque sem ac vulputate congue. Duis aliquet eget nunc id vestibulum. Proin ut sem quis tortor bibendum semper finibus non quam."
				+ "Integer nunc enim, ultricies sit amet sem sit amet, imperdiet vulputate tellus. Sed auctor erat non neque venenatis, vitae posuere turpis sodales. Ut dapibus vestibulum est id gravida. Vestibulum ullamcorper, diam vitae dictum gravida, mauris orci mattis orci, id pharetra tortor mi et odio. Etiam eget enim ligula. Cras malesuada est gravida blandit tincidunt. Vivamus eu euismod neque. Fusce scelerisque, leo ut venenatis fermentum, elit libero pretium libero, at lobortis diam tortor nec urna. Curabitur eget justo sagittis purus blandit accumsan luctus et ex. Maecenas magna risus, volutpat at sem sit amet, commodo porta ante. Mauris et congue diam, a egestas ligula. Aliquam convallis arcu ultricies, pellentesque sem at, tempor eros. Sed sit amet consectetur felis. Mauris volutpat tortor vel nisl volutpat posuere. Nam eu odio odio."
				+ "Nullam semper diam ligula, vitae accumsan magna ultrices nec. Nam eget erat tempus, hendrerit est sit amet, ultricies sem. Donec auctor sapien orci, id maximus dui vulputate ac. Curabitur ut mi at tortor egestas tincidunt nec vel nisl. Aliquam et suscipit magna. Sed accumsan neque elit, finibus aliquet lacus pretium ac. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque semper mi erat, nec facilisis est cursus eget. Phasellus dignissim ante mi, quis mattis orci vehicula vulputate. Duis massa ex, facilisis id mauris id, imperdiet sagittis turpis. In id sapien lacus. Mauris cursus convallis diam ullamcorper bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam tortor libero, egestas sit amet egestas at, mattis in elit. Nulla facilisi. Ut luctus, eros sed viverra faucibus, nibh orci imperdiet nisl, eu faucibus nisl eros nec odio."
				+ "Donec eu convallis dui. Nunc facilisis quam ut augue gravida, et auctor mi mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut nec ultricies leo, sit amet ornare metus. Phasellus fermentum at risus sed."; 
		
		inicio = System.currentTimeMillis();
        padroes.forEach(padrao -> {
        	ForcaBruta.executar(texto500Palavras, padrao);        	
        });
        duracao = System.currentTimeMillis() - inicio;
        System.out.println("Texto com 500 palavras");
        System.out.println("Tempo (ms): " + duracao);
		
        inicio = System.currentTimeMillis();
        padroes.forEach(padrao -> {
        	ForcaBruta.executar(texto1000Palavras, padrao);        	
        });
        duracao = System.currentTimeMillis() - inicio;
        System.out.println("Texto com 1000 palavras");
        System.out.println("Tempo (ms): " + duracao);
        
        inicio = System.currentTimeMillis();
        padroes.forEach(padrao -> {
        	ForcaBruta.executar(texto1500Palavras, padrao);        	
        });
        duracao = System.currentTimeMillis() - inicio;
        System.out.println("Texto com 1500 palavras");
        System.out.println("Tempo (ms): " + duracao);
        
        inicio = System.currentTimeMillis();
        padroes.forEach(padrao -> {
        	ForcaBruta.executar(texto2000Palavras, padrao);        	
        });
        duracao = System.currentTimeMillis() - inicio;
        System.out.println("Texto com 2000 palavras");
        System.out.println("Tempo (ms): " + duracao);
        
        inicio = System.currentTimeMillis();
        padroes.forEach(padrao -> {
        	ForcaBruta.executar(texto5000Palavras, padrao);        	
        });
        duracao = System.currentTimeMillis() - inicio;
        System.out.println("Texto com 5000 palavras");
        System.out.println("Tempo (ms): " + duracao);
	}
}
